name: Deploy Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master
      
jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run deploy -- --token "${{ secrets.FIREBASE_TOKEN }}"